GRUB: support custom themes + bring configuration closer to grml-live defaults
Now that we support $prefix instead of hardcoded /boot/grub usage in our
GRUB configuration files (see
https://github.com/grml/grml-live/pull/548), we can also support custom
GRUB themes and alike.

Set up `grub` directory in tftpboot directory (/var/lib/tftpboot by
default) for booting GRUB via PXE/netboot, providing all files that
might be relevant for booting.

Avoid rewriting the configuration files on the fly, and instead bring
grub.cfg as close as possible to what we're using on the live system
also (the GRUB netboot binary sadly doesn't neither support sourcing
files with regexp nor testing for files with [ -e ....]).

NOTE: we are *not* setting up / including `addons.cfg`, as all entries
are known to be failing (the test for the files all fail as stated in
the previous paragraph already), even when removing the tests and
adjusting the paths to use $prefix/../addons/ instead of /boot/addons/,
it doesn't work and chainloading the addons via PXE/netboot fail with:

  error: Access violation

See https://github.com/grml/grml-live/issues/321